-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 21:49:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ticket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket` DEFAULT CHARACTER SET utf8 ;
USE `ticket` ;

-- -----------------------------------------------------
-- Table `ticket`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`user` (
  `user_id` INT(11) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_type` ENUM('user', 'admin') NOT NULL,
  `activation_code` VARCHAR(255) NOT NULL,
  `email_status` ENUM('0', '1') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`ticket` (
  `ticket_id` INT NOT NULL,
  `ticket_type` ENUM('system', 'other') NULL,
  `ticket_title` VARCHAR(255) NULL,
  `ticket_description` TEXT NULL,
  `ticket_image` VARCHAR(255) NULL,
  `ticket_status` ENUM('issued', 'approved', 'in-progress', 'reject', 'assigned', 'solved') NULL,
  `ticket_priority` ENUM('low', 'medium', 'high') NULL,
  `due_date` DATETIME NULL,
  `info` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`ticket_id`, `user_id`),
  INDEX `fk_ticket_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_ticket_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticket`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`contact` (
  `contact_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `description` TEXT NULL,
  `contact_status` ENUM('0', '1') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`contact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket`.`notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`notify` (
  `notify_id` INT NOT NULL,
  `notify_title` VARCHAR(255) NULL,
  `notify_description` TEXT NULL,
  `notify_status` ENUM('0', '1') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`notify_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
